version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo def region $AWS_DEFAULT_REGION
      - echo ${APPLICATION_NAME}
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - cd infrastructure-microservices
      - cd config-service
      - mvn clean install
      - IMAGE_TAG_CONFIG=config

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls
      - docker-compose --file=docker-compose.yml build

      - echo build config-service
      - docker build -t $REPOSITORY_URI_CONFIG_SERVICE:latest ./infrastructure-microservices-module/config-service
      - docker tag $REPOSITORY_URI_CONFIG_SERVICE:latest $REPOSITORY_URI_CONFIG_SERVICE:latest


  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose --file=docker-compose.yml push

      - echo push config
      - docker push $REPOSITORY_URI_CONFIG_SERVICE:latest

artifacts:
  files:
    - '**/*'
