version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre build
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`

