version: 0.2

phases:
  install:
    commands:
      - cp config-files/settings.xml /root/.m2/settings.xml
  pre_build:
    commands:
      - echo Pre build
      - pip3 install awscli --upgrade --user
      - echo prepare codeartifact token
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain transport-exchange --domain-owner 908085288135 --query authorizationToken --output text`
  build:
    commands:
      - echo Started build for last commit $CODEBUILD_SOURCE_VERSION
      - echo Start build phase `date`
      - mvn clean install deploy
      - echo DEPLOY ARTIFACTS

artifacts:
  files:
    - '**/*'
