##########################################################
##########            PROD CONFIGURATION       ###########
##########        TRANSPORT EXCHANGE SERVICE   ###########
##########################################################

security:
  oauth2:
    client:
      clientId: transport-exchange-service
      clientSecret: ${TRANSPORT-EXCHANGE-SERVICE-PASSWORD}
      accessTokenUri: http://auth-service:5000/oauth/token
      grant-type: client_credentials
      scope: server

server:
  port: 8082


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000


spring:
  application:
    name: transport-exchange-service

  ##################### DATA SOURCE ############################################
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
    initialization-mode: always
  ##################### JPA USED SPRING DATA #####################################
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        event:
          merge:
            entity_copy_observer: allow
      use_sql_comments: true
    show-sql: true


