##########################################################
##########            DEV CONFIGURATION        ###########
##########            COMMON PROPERTIES        ###########
##########################################################


logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/api/discovery-service/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:5000/users/current
