spring:
  application:
    name: notification-service



  ##################### SPRING MAIL PROPERTIES #################################
  mail:
    host: smtp.mail.ru
    username: transport-exchange@mail.ru
    password: panteon1172
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages
    encoding: UTF-8

server:
  port: 3000


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000