##########################################################
##########            PROD CONFIGURATION       ###########
##########            ACCOUNT_SERVICE          ###########
##########################################################

security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://config.panteontrans.be/api/auth-service/oauth/token
      grant-type: client_credentials
      scope: server

server:
  port: 6000


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000


spring:
  application:
    name: account-service

  ##################### DATA SOURCE ############################################
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
    initialization-mode: always
    url: jdbc:postgresql://nikita-db.csjgoepskieq.eu-central-1.rds.amazonaws.com:5432/account
    username: account_app
    password: account_pw
  ##################### JPA USED SPRING DATA #####################################
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
      use_sql_comments: true
    show-sql: true


