##########################################################
##########            PROD CONFIGURATION       ###########
##########            COMMON PROPERTIES        ###########
##########################################################


logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://transport-exchange-lb-1181109775.eu-central-1.elb.amazonaws.com/api/discovery-service/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://config.panteontrans.be/api/auth-service/users/current

