##########################################################
##########            PROD CONFIGURATION       ###########
##########            COMMON PROPERTIES        ###########
##########################################################


logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://config.panteontrans.be:8761/eureka/

security:
  oauth2:
    resource:
      user-info-uri: http://config.panteontrans.be/api/auth-service/users/current

security.basic.enable: false
security.ignored: /**
