##########################################################
##########            PROD CONFIGURATION       ###########
##########            AUTH SERVICE             ###########
##########################################################


##################### SERVER PROP #################################
server:
  port: 5000

##################### SPRING GLOBAL #################################

spring:
  application:
    name: auth-service

  ##################### DATA SOURCE #################################
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    url: jdbc:postgresql://nikita-db.csjgoepskieq.eu-central-1.rds.amazonaws.com:5432/auth
    username: auth_app
    password: auth_pw
  ##################### JPA USED SPRING DATA #################################
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      format-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
      use_sql_comments: true
    show-sql: true


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000


