##########################################################
##########            PROD CONFIGURATION       ###########
##########        TRANSPORT EXCHANGE SERVICE   ###########
##########################################################

# security:
#   oauth2:
#     client:
#       clientId: transport-exchange-service
#       clientSecret: ${TRANSPORT-EXCHANGE-SERVICE-PASSWORD}
#       accessTokenUri: http://config.panteontrans.be/api/auth-service/oauth/token
#       grant-type: client_credentials
#       scope: server

server:
  port: 8082


feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000


spring:
  application:
    name: transport-exchange-service

  ##################### DATA SOURCE ############################################
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
    initialization-mode: always
    url: jdbc:postgresql://nikita-db.csjgoepskieq.eu-central-1.rds.amazonaws.com:5432/transport_exchange
    username: transport_exchange_app
    password: transport_exchange_pw
  ##################### JPA USED SPRING DATA #####################################
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      format-sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        event:
          merge:
            entity_copy_observer: allow
      use_sql_comments: true
    show-sql: true


security.basic.enable: false
security.ignored: /**
