version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo def region $AWS_DEFAULT_REGION
      - echo ${APPLICATION_NAME}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - mvn clean install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls
      - docker-compose --file=docker-compose-prod.yml build
      - echo build config
      - docker build -t infrastructure-microservices-module/config:latest .
      - docker tag $REPOSITORY_URI:latest infrastructure-microservices-module/config:$config
      - echo build registry
      - docker build -t infrastructure-microservices-module/registry:latest .
      - docker tag $REPOSITORY_URI:latest infrastructure-microservices-module/registry:registry
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose --file=docker-compose-prod.yml push
      - echo push config
      - docker push $REPOSITORY_URI:config
      - echo push registry
      - docker push $REPOSITORY_URI:registry
artifacts:
  files:
    - 'Dockerrun.aws.json'