version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - echo def region $AWS_DEFAULT_REGION
      - echo ${APPLICATION_NAME}
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - mvn clean install
      - IMAGE_TAG_CONFIG=config
      - IMAGE_TAG_NGINX=nginx
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - ls
      - docker-compose --file=docker-compose-prod.yml build

      - echo build config
      - docker build -t $REPOSITORY_URI_CONFIG:latest ./infrastructure-microservices-module/config
      - docker tag $REPOSITORY_URI_CONFIG:latest $REPOSITORY_URI_CONFIG:$IMAGE_TAG_CONFIG


      - echo build ngix
      - docker build -t $REPOSITORY_URI_NGINX:latest ./infrastructure-microservices-module/nginx
      - docker tag $REPOSITORY_URI_NGINX:latest $REPOSITORY_URI_NGINX:$IMAGE_TAG_NGINX

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker-compose --file=docker-compose-prod.yml push
      - echo push config
      - docker push $REPOSITORY_URI_CONFIG:$IMAGE_TAG_CONFIG
      - echo push ngix
      - docker push $REPOSITORY_URI_NGINX:$IMAGE_TAG_NGINX
artifacts:
  files:
    - 'Dockerrun.aws.json'