
server:
  port: 8888

---
spring:
  profiles:
    active: prod
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}

---
spring:
  profiles:
    active: dev #prod!
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IlyaChakun/panteon-trans/
          search-paths:
            - "services-config-files/{profile}"

  security:
    user:
      password: ${CONFIG_SERVICE_PASSWORD}
